/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClinicalFactorsRouteImport } from './routes/clinical-factors'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as RiskAnalysisRouteImport } from './routes/risk-analysis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicalFactorsRoute = ClinicalFactorsRouteImport.update({
  id: '/clinical-factors',
  path: '/clinical-factors',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskAnalysisRoute = RiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clinical-factors': typeof ClinicalFactorsRoute
  '/insights': typeof InsightsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clinical-factors': typeof ClinicalFactorsRoute
  '/insights': typeof InsightsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clinical-factors': typeof ClinicalFactorsRoute
  '/insights': typeof InsightsRoute
  '/risk-analysis': typeof RiskAnalysisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/clinical-factors' | '/insights' | '/risk-analysis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/clinical-factors' | '/insights' | '/risk-analysis'
  id: '__root__' | '/' | '/clinical-factors' | '/insights' | '/risk-analysis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClinicalFactorsRoute: typeof ClinicalFactorsRoute
  InsightsRoute: typeof InsightsRoute
  RiskAnalysisRoute: typeof RiskAnalysisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinical-factors': {
      id: '/clinical-factors'
      path: '/clinical-factors'
      fullPath: '/clinical-factors'
      preLoaderRoute: typeof ClinicalFactorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-analysis': {
      id: '/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/risk-analysis'
      preLoaderRoute: typeof RiskAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClinicalFactorsRoute: ClinicalFactorsRoute,
  InsightsRoute: InsightsRoute,
  RiskAnalysisRoute: RiskAnalysisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
